
services:
  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: rss_feeds_document
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    # networks:
    #   - put_net
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro